[env]
upload_port = COM14
monitor_port = COM14
framework = arduino
board_build.filesystem = spiffs
board_build.partitions = no_ota.csv
monitor_speed = 115200
upload_speed = 921600
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps =
	Adafruit NeoPixel@1.12.4
	ArduinoJson@7.3.1
	esp32async/ESPAsyncWebServer@3.8.0
	https://github.com/FabulosoDev/PN5180-Library.git#esp8266_spi

[env:d1_mini]
platform = espressif8266
board = d1_mini
lib_deps =
	${env.lib_deps}
	esp32async/ESPAsyncTCP@2.0.0

[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
lib_deps =
	${env.lib_deps}
	esp32async/AsyncTCP@3.4.8

[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
lib_deps =
	${env.lib_deps}
	esp32async/AsyncTCP@3.4.8
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
